// <auto-generated />
using LearningLogAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningLogAPI.Migrations
{
    [DbContext(typeof(CourseInfoContext))]
    [Migration("20250729145730_InitialCourseSeedData")]
    partial class InitialCourseSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("LearningLogAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSnippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavoritedByCurrentUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedInVideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialDocsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalNotesUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeSnippet = "ng new angular-app-name --routing",
                            Description = " This course guides you through the essential setup steps and introduces the core concepts",
                            Difficulty = "Easy,☕ Coffee’s Still Hot ",
                            Duration = "3 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/installation",
                            PersonalNotesUrl = "https://example.com/personal-notes",
                            Review = "Great course! Clear explanations and practical examples. Helped me understand how Signals differ from RxJS.",
                            Tags = "[\"angular\",\"setup\",\"cli\",\"environment\"]",
                            Title = "Installation and Setup"
                        },
                        new
                        {
                            Id = 2,
                            CodeSnippet = "ng new angular-app-name --no-standalone",
                            Description = "Discover how traditional Angular components shape your application's user interface.",
                            Difficulty = "Medium, 😅 Coffee’s Lukewarm ",
                            Duration = "1 hour",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/components",
                            PersonalNotesUrl = "https://example.com/personal-notes",
                            Review = "Solid breakdown of component architecture. Loved the examples and visual explanations.",
                            Tags = "[\"angular\",\"components\",\"architecture\"]",
                            Title = "Traditional Components"
                        },
                        new
                        {
                            Id = 3,
                            CodeSnippet = "ng new angular-app-name --routing",
                            Description = "Learn how standalone components simplify Angular development by removing the need for NgModules.",
                            Difficulty = "Medium, 😅 Coffee’s Lukewarm ",
                            Duration = "3 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/ngmodules/overview",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EbWVAQEt6clNg4FOj6DjT_0BE1hzYFiW496P2kDFuQyQ2A?e=pEBArL",
                            Review = "Helped me understand when to use standalone components and how they simplify module management.",
                            Tags = "[\"angular\",\"standalone\",\"modules\"]",
                            Title = "Standalone Components"
                        },
                        new
                        {
                            Id = 4,
                            CodeSnippet = "<[src]=\"imageUrl\" (click)=\"onClick()\">",
                            Description = "Dive into data binding in Angular and learn how it connects your application's logic to the user interface.",
                            Difficulty = "Medium, 😅 Coffee’s Lukewarm",
                            Duration = "10 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/templates/binding",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/ERt6Sa8K_hlPvgT7x-qexNYB2ElfrdJOdat1LjY0x7C7aA?e=9bWr4q",
                            Review = "Covers all titles of binding clearly—property, event, and two-way.",
                            Tags = "[\"angular\",\"binding\",\"data\"]",
                            Title = "Binding"
                        },
                        new
                        {
                            Id = 5,
                            CodeSnippet = "constructor(private http: HttpClient) {}",
                            Description = "Explore how Angular’s dependency injection system simplifies code management and promotes modular design.",
                            Difficulty = "Hard, 🔥 Coffee’s Cold & You’re Debugging",
                            Duration = "7 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/di",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EX7sZfCwHQhKnzIN-97M7JoBxNImanMiF17J-0QaeRYpOA?e=gmr2Aj",
                            Review = "DI is powerful once you understand providers and injectors.",
                            Tags = "[\"angular\",\"di\",\"services\"]",
                            Title = "Dependency Injection"
                        },
                        new
                        {
                            Id = 6,
                            CodeSnippet = "getCourses(): Observable<Course[]> {}",
                            Description = "You'll learn how Observables work under the hood, how to create and subscribe to them, and how they integrate with Angular services and HTTP requests. ",
                            Difficulty = "Medium, 😅 Coffee’s Lukewarm",
                            Duration = "8 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/http/making-requests#http-observables",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EaWGsN0Y82NMjdUKk2PvuewBTytPCXvtZJPSI5GRUoPnRQ?e=D7ieSK",
                            Review = "This course provides a solid foundation in using Observables within Angular. The explanations are clear, and the examples are practical, especially the sections on HTTP requests and reactive forms. ",
                            Tags = "[\"angular\",\"observables\",\"architecture\"]",
                            Title = "Observables"
                        },
                        new
                        {
                            Id = 7,
                            CodeSnippet = "interface Course { title: string; duration: string; }",
                            Description = "Understand how interfaces in Angular help define the shape of data and enforce title safety. .",
                            Difficulty = "Easy, ☕ Coffee’s Still Hot!",
                            Duration = "1 hour",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://www.titlescriptlang.org/docs/handbook/interfaces.html",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/Ef0L5QPwdIhDh6O5mwUsDT8BSFd4XixbgPtUKibjGv6YMg?e=YWEdca",
                            Review = "Interfaces help enforce structure and improve title safety.",
                            Tags = "[\"titlescript\",\"interfaces\",\"typing\"]",
                            Title = "Interface"
                        },
                        new
                        {
                            Id = 8,
                            CodeSnippet = "path: 'dashboard', component: DashboardComponent",
                            Description = "Master Angular’s routing and navigation system to build seamless, single-page applications..",
                            Difficulty = "Hard, 🔥 Coffee’s Cold & You’re Debugging",
                            Duration = "10 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/routing",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EWk_eXAQUxNCu0mquUqx55UBqCQ3vdI9djOP5M6bYrzy5A?e=Qtci4r",
                            Review = "Routing was tricky at first, but guards and lazy loading made it click.",
                            Tags = "[\"angular\",\"routing\",\"navigation\"]",
                            Title = "Routing and Navigation"
                        },
                        new
                        {
                            Id = 9,
                            CodeSnippet = "this.form = new FormGroup({ name: new FormControl('') });",
                            Description = "Gain a deep understanding of reactive forms in Angular and how they enable dynamic, scalable form handling.",
                            Difficulty = "Hard, 🔥 Coffee’s Cold & You’re Debugging",
                            Duration = "5 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/forms",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/ETMwO2Wy501MooBVP2HgDm0Bs_q0p04aMtYoSMOgfzcQXg?e=3irLJZ",
                            Review = "Reactive forms are powerful for validation and dynamic controls.",
                            Tags = "[\"angular\",\"forms\",\"reactive\"]",
                            Title = "Reactive Forms"
                        },
                        new
                        {
                            Id = 10,
                            CodeSnippet = "source$.pipe(map(val => val * 2))",
                            Description = "Unlock the power of RxJS operators to transform, filter, and manage streams of data in Angular.",
                            Difficulty = "Hard, 🔥 Coffee’s Cold & You’re Debugging",
                            Duration = "9 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://rxjs.dev/guide/operators",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EUlGHXl5Hr1MpAv71ozZHPkBNZOnoL424hzifdL9g-LDfg?e=tlyRkG",
                            Review = "RxJS is a beast, but once you get map, mergeMap, and switchMap, it’s 🔥.",
                            Tags = "[\"rxjs\",\"observables\",\"operators\"]",
                            Title = "RxJS Operators"
                        },
                        new
                        {
                            Id = 11,
                            CodeSnippet = "expect(component.title).toEqual('MyApp')",
                            Description = "Learn how to write effective tests and debug Angular applications with confidence. .",
                            Difficulty = "Hard, 🔥 Coffee’s Cold & You’re Debugging",
                            Duration = "10 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.dev/guide/testing",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/ETb__BB221ZOtU4YlMOh2V0BE_cAZuJAaSHDKeP7jPQzEw?e=eLbKHK",
                            Review = "Unit testing with Jasmine and Karma was easier than expected. Debugging tips were gold.",
                            Tags = "[\"angular\",\"testing\",\"debugging\"]",
                            Title = "Testing & Debugging"
                        },
                        new
                        {
                            Id = 12,
                            CodeSnippet = "<img [src]=\"imageUrl\"> {{ birthday | date:'longDate' }}",
                            Description = "Explore additional Angular features including working with images, creating and using pipes, and handling advanced syntax.",
                            Difficulty = "Easy, ☕ Coffee’s Still Hot!",
                            Duration = "2 hours",
                            Img = "favicon.ico",
                            IsFavoritedByCurrentUser = false,
                            LinkedInVideoUrl = "https://www.linkedin.com/learning/learning-angular-25357291/learning-angular?resume=false&u=262938922",
                            OfficialDocsUrl = "https://angular.io/",
                            PersonalNotesUrl = "https://pulte-my.sharepoint.com/:w:/p/maholder/EQmlfz-xClhOjw6FhsdaT4ABswVDOw6XNIlYfdsLbvpZcA?e=aUS0Jk",
                            Review = "A fun wrap-up of random but useful Angular tricks.",
                            Tags = "[\"angular\",\"extras\",\"tips\"]",
                            Title = "Extras"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
